name: Create Github Release

on:
  push:
    branches:
      - main

jobs:
  create_release_if_possible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Get NPM Version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Check if Tag exists
        uses: mukunku/tag-exists-action@v1.4.0
        id: checkTag
        with:
          tag: ${{ steps.package-version.outputs.current-version}}

      - name: Create Release if Tag is new
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          release_name: v${{ steps.package-version.outputs.current-version}}
          draft: false
          prerelease: false

      - name: Publish on NPM
        if: ${{ steps.checkTag.outputs.exists == 'false' }}
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
